---
title: "Analysis"
author: "Coline Caillon"
date: '2026-02-11'
output: github_document
---

Project infos here

# Demultiplexing

coming soon


# Read Trimming, Mapping, and SNP Calling

Create a new working directory for using dDocent (ref dDocent here)

```{bash}
cd /home/ccaillon
mkdir RISG_dDocent_working
cd RISG_dDocent_working

#Activate working environment
conda init
conda activate RISG_Seascape
```

```{bash}
cd /home/ccaillon/RISG_dDocent_working

#Create symbolic links
ln -s /home/Shared_Data/ROD_CADO/analysis/dDocent_ngs #link dDocent file into this new working directory
ln -s ../../Shared_Data/RISG_Adults/final_demuliplexed_files_for_Coline/*.fq.gz . #link raw seq files into working directory
ln -s /home/Genomic_Resources/C_virginica/reference.fasta #link new haplotig masked genome into working directory
```

## Read Trimming

First run dDocent_ngs for only Read Trimming.

```{bash}
./dDocent_ngs
```

dDocent 3.0.0 

239 individuals are detected. Is this correct? Enter yes or no and press [ENTER]
yes
Proceeding with 60 individuals
dDocent detects 80 processors available on this system.
Please enter the maximum number of processors to use for this analysis.
20

Do you want to quality trim your reads?
Type yes or no and press [ENTER]?
yes

Do you want to perform an assembly?
Type yes or no and press [ENTER].
no

Reference contigs need to be in a file named reference.fasta

Do you want to map reads?  Type yes or no and press [ENTER]
no

Mapping will not be performed
Do you want to use FreeBayes to call SNPs?  Please type yes or no and press [ENTER]
no

Please enter your email address.  dDocent will email you when it is finished running.
Don't worry; dDocent has no financial need to sell your email address to spammers.

At this point, all configuration information has been entered and dDocent may take several hours to run.
It is recommended that you move this script to a background operation and disable terminal input and output.
All data and logfiles will still be recorded.
To do this:
Press control and Z simultaneously
Type bg and press enter
Type disown -h and press enter
Now sit back, relax, and wait for your analysis to finish

Trimming reads
\
dDocent has finished with an analysis in /home/ccaillon/RISG_dDocent_working
dDocent started Thu Feb 12 11:31:49 EST 2026
dDocent finished Thu Feb 12 12:03:38 EST 2026

Before continuing with dDocent, checking the quality of the trimmed reads with FastQC

```{bash}
cd /home/ccaillon/RISG_dDocent_working

mkdir cleanedreads_fastqc_results
cd cleanedreads_fastqc_results

fastqc -o . /home/ccaillon/RISG_dDocent_working/*.R1.fq.gz
fastqc -o . /home/ccaillon/RISG_dDocent_working/*.R2.fq.gz
```

```{bash}
multiqc .
#Rename:
mv multiqc_report.html cleanedreads_multiqc_report.html
```

MultiQC report can be viewed here.
Everything looks good. All the sequences and adapter contents are in the green zone for quality check. All individuals have adapter content <1%, except MW_CB_3401 which does have higher adapter content but it's still a very small percentage (1.66%). MW_CB_3401 also have higher overrepresented sequences (red zone for quality check). It should not be problematic, since it's common for reduced representation sequencing to share common fragments. Keep an eye if these have significant impacts on MW_CB_3401 individual's downstream analyses.
Conclusion after meeting with Jon: More reads are linked to more adapter contents, and because these adapter contents are repetitive sequences it's also linked to higher overrepresented sequences. Typically, if a sample has more adapter content than others, that can means that the quality of the DNA was not as good going in, and so it ends up with shorter fragments. And the higher adapter content is linked to more overrepresented sequences because PCR biases favor smaller fragments. Jon confirms this is not a concern to have such low levels of adapter contents (2% or less) for downstream analyses.

## Read Mapping

Make sure reference.fasta file is in the directory.

Run dDocent again for Read Mapping. Make sure to run the program in the same directory where the trimmed reads (R1 and R2) files are located, no need to run the trimming again.
Reads are mapped (aligned to reference sequences) using the MEM algorithm of BWA and a scoring system to decide which alignment is best with three parameters: match score value (A), mismatch score (B), and gap opening penalty (O).
I want to test out the optimal mapping parameter values before moving forward. Rather than running the dDocent mapping on all the samples, I'm going to save a subset of individuals into a new directory and perform the mapping test on that subset.
Two individuals are selected per bay: one from a population located at the mouth of the bay and one from an upper-bay population, in order to represent a wide spatial gradient.
Sites/Individuals: 
- BIS_NB_1
- PVD_NB_1
- CS_DB_3000
- HC_DB_3031
- HI_CB_3151
- MW_CB_3391
Use samtools flagstats on individual sample files too see how well the mapping worked. I look for which parameters result in the highest percentage of properly paired and lowest percentage of singletons.

Test 1: I'm going to use the default mapping parameters as A = 1, B = 4, and O = 6.
```{bash}
cd /home/ccaillon/RISG_dDocent_working
mkdir mapping_test
cd mapping_test

ln -s ../BIS_NB_1.* .
ln -s ../PVD_NB_1.* .
ln -s ../CS_DB_3000.* .
ln -s ../HC_DB_3031.* .
ln -s ../HI_CB_3151.* .
ln -s ../MW_CB_3391.* .
ln -s ../reference.fasta .
ln -s ../dDocent_ngs .

./dDocent_ngs
```

Use samtools flagstats to investigate bam files
```{bash}
samtools flagstats -@16 BIS_NB_1.F.bam #change the threads with -@16 to make things run faster
samtools flagstats -@16 PVD_NB_1.F.bam
samtools flagstats -@16 CS_DB_3000.F.bam
samtools flagstats -@16 HC_DB_3031.F.bam
samtools flagstats -@16 HI_CB_3151.F.bam
samtools flagstats -@16 MW_CB_3391.F.bam
```

Test 2: Mapping parameter values as A=1, B=3, and O=5 (mostly used in Jonathan Puritz's lab)
```{bash}
cd /home/ccaillon/RISG_dDocent_working/mapping_test
#Run again dDocent in mapping_test directory with the new mapping parameters.
```
Outputs: More passed reads, higher percentage of properly paired reads, and a lower percentage of singletons compared with Test 1 (default parameters).

Test 3: Mapping parameter values as A=2, B=4, and O=6 (optimal parameters of Amy Zyck on NB Seascape Genomics project)
```{bash}
cd /home/ccaillon/RISG_dDocent_working/mapping_test
#Run again dDocent in mapping_test directory with the new mapping parameters.
```
Outputs: Even more passed reads, higher percentage of properly paired reads, and a lower percentage of singletons than Test 2.

Test 4: Mapping parameter values as A=3, B=5, and O=7 (higher values than the default for all three parameters)
```{bash}
cd /home/ccaillon/RISG_dDocent_working/mapping_test
#Run again dDocent in mapping_test directory with the new mapping parameters.
```
Outputs: Less passed reads than Test 2 and Test 3, but higher percentage of properly paired reads and lower percentage of singletons than Test 2 and Test 3.

Test 5: Mapping parameter values as A=2, B=3, and O=5
```{bash}
cd /home/ccaillon/RISG_dDocent_working/mapping_test
#Run again dDocent in mapping_test directory with the new mapping parameters.
```
Outputs: Even less passed reads than Test 4, but highest percentage of properly paired and lowest percentage of singletons among all test.

Test 6: Mapping parameter values as A=2, B=5, and O=7
```{bash}
cd /home/ccaillon/RISG_dDocent_working/mapping_test
#Run again dDocent in mapping_test directory with the new mapping parameters.
```
Outputs: Highest passed reads among all tests, but percentage of properly paired reads and singletons not as good as Test 3.

Conclusion of outputs:
Add table resuming outputs here.
Mapping parameter values A=2, B=4, O=6 is the best option. Even if Test 3 (Amy Zyck's optimal parameters: A=2, B=4, O=6) doesn't top every individual metric, selecting for the best overall compromise across passed reads, properly paired reads, and singleton rates is the right approach for downstream consistency.

Run again dDocent_ngs in the main working directory using the optimal mapping parameter values A=2, B=4, O=6
```{bash}
cd /home/ccaillon/RISG_dDocent_working
./dDocent_ngs
```

dDocent 3.0.0 

239 individuals are detected. Is this correct? Enter yes or no and press [ENTER]
yes
Proceeding with 60 individuals
dDocent detects 80 processors available on this system.
Please enter the maximum number of processors to use for this analysis.
20

Do you want to quality trim your reads?
Type yes or no and press [ENTER]?
no

Do you want to perform an assembly?
Type yes or no and press [ENTER].
no

Reference contigs need to be in a file named reference.fasta

Do you want to map reads?  Type yes or no and press [ENTER]
yes
BWA will be used to map reads.  You may need to adjust -A -B and -O parameters for your taxa.
Would you like to enter a new parameters now? Type yes or no and press [ENTER]
yes
Please enter new value for A (match score).  It should be an integer.  Default is 1.
2
Please enter new value for B (mismatch score).  It should be an integer.  Default is 4.
4
Please enter new value for O (gap penalty).  It should be an integer.  Default is 6.
6

Do you want to use FreeBayes to call SNPs?  Please type yes or no and press [ENTER]
no

Please enter your email address.  dDocent will email you when it is finished running.
Don't worry; dDocent has no financial need to sell your email address to spammers.

At this point, all configuration information has been entered and dDocent may take several hours to run.
It is recommended that you move this script to a background operation and disable terminal input and output.
All data and logfiles will still be recorded.
To do this:
Press control and Z simultaneously
Type bg and press enter
Type disown -h and press enter
Now sit back, relax, and wait for your analysis to finish

Using BWA to map reads

dDocent has finished with an analysis in /home/ccaillon/RISG_dDocent_working
dDocent started Wed Feb 25 10:58:32 EST 2026
dDocent finished Thu Feb 26 22:57:35 EST 2026

## SNP Calling

Run dDocent again to call variants using FreeBayes. FreeBayes is a Bayesian-based variant detection program that uses assembled haplotype sequences to simultaneously call SNPs, INDELS, multi-nucleotide polymorphisms (MNPs), and complex events (composite insertion and substitution events) from alignment files (.bam files). At the end, raw SNP calls are concatenated into a single variant call file (VCF) using VCFtools.

```{bash}
cd /home/ccaillon/RISG_dDocent_working
./dDocent_ngs
```

dDocent version 3.0.0 started Fri Feb 27 08:54:38 EST 2026 

239 individuals are detected. Is this correct? Enter yes or no and press [ENTER]
Proceeding with 239 individuals
dDocent detects 80 processors available on this system.
Please enter the maximum number of processors to use for this analysis.
20

Do you want to quality trim your reads?
Type yes or no and press [ENTER]?
no

Do you want to perform an assembly?
Type yes or no and press [ENTER].
no

Reference contigs need to be in a file named reference.fasta

Do you want to map reads?  Type yes or no and press [ENTER]
no
Mapping will not be performed

Do you want to use FreeBayes to call SNPs?  Please type yes or no and press [ENTER]
yes

Please enter your email address.  dDocent will email you when it is finished running.
Don't worry; dDocent has no financial need to sell your email address to spammers.

To do this:
Press control and Z simultaneously
Type bg and press enter
Type disown -h and press enter
Now sit back, relax, and wait for your analysis to finish

Using FreeBayes to call SNPs

dDocent has finished with an analysis in /home/ccaillon/RISG_dDocent_working
dDocent started Fri Feb 27 08:54:38 EST 2026
dDocent finished Tue Mar 3 00:51:21 EST 2026 (~88hours)

After filtering, kept 25955636 out of a possible 70386649 Sites

## SNP Filtering

Use PVCF_filter.sh script as a first step filter, it's going to be faster. This script automatically filters genotype calls based on several criteria: genotypes with less than 75% presence across all individuals, a minimum quality score of 20, and a minimum read depth of 5 (genotypes with less than 5 reads as missing). It also separates nDNA (nuclear DNA) from mtDNA (mitochondrial DNA). Downstream analyses continue with nDNA, separating SNPs and INDELs while retaining only the SNPs.

```{bash}
#We need to run this script within the new directory raw.vcf created by dDocent
cd /home/ccaillon/RISG_dDocent_working/raw.vcf

#Copy the PVCF_filter.sh script from ROD_CADO directory
cp /home/Shared_Data/ROD_CADO/analysis/raw.vcf/PVCF_filter.sh /home/ccaillon/RISG_dDocent_working/raw.vcf/

#Activate conda environment 
conda activate ROD_CADO

#Run
./PVCF_filter.sh TRS 20
```

This script will automatically filter a FreeBayes generated VCF file using criteria related to site depth,
quality versus depth, allelic balance at heterzygous individuals, and paired read representation.
The script assumes that loci and individuals with low call rates (or depth) have already been removed. 

Number of sites filtered based on allele balance at heterozygous loci, locus quality, and mapping quality / Depth
 190133 of 2092541 
 
Number of additional sites filtered based on properly paired status
 8110 of 1902408 

Number of sites filtered based on high depth and lower than 2*DEPTH quality score
 338665 of 1902408 

                                                Histogram of mean depth per site                                        
     180000 +-------------------------------------------------------------------------------------------------------+   
            |*****    +     +    +    +    +    +     +    +    +    +    +     +    +    +    +    +     +    +    |   
            |    *                                        'meandepthpersite' using (bin($1,binwidth)):(1.0) ******* |   
     160000 |-+  *                                                                                                +-|   
            |    *                                                                                                  |   
     140000 |-+  *                                                                                                +-|   
            |    ******                                                                                             |   
            |    *    *                                                                                             |   
     120000 |-+  *    *                                                                                           +-|   
            |    *    *******                                                                                       |   
     100000 |-+  *    *     *                                                                                     +-|   
            |    *    *     *                                                                                       |   
            |    *    *     ******                                                                                  |   
      80000 |-+  *    *     *    *                                                                                +-|   
            |    *    *     *    ******                                                                             |   
      60000 |-+  *    *     *    *    ******                                                                      +-|   
            |    *    *     *    *    *    *                                                                        |   
            |    *    *     *    *    *    ************                                                             |   
      40000 |-+  *    *     *    *    *    *    *     *                                                           +-|   
            |    *    *     *    *    *    *    *     *                                                             |   
      20000 |-+  *    *     *    *    *    *    *     *                                                           +-|   
            |    *    *     *    *    *    *    *     *                                                             |   
            |    *    *     *    *    *    *    *     ******************************************    +     +    +    |   
          0 +-------------------------------------------------------------------------------------------------------+   
            10   11   12    13   14   15   16   17    18   19   20   21   22    23   24   25   26   27    28   29   30  
                                                           Mean Depth                                                   
                                                                                                                        
The 95% cutoff would be 24
Would you like to use a different maximum mean depth cutoff than 24, yes or no
Maximum mean depth cutoff is 24

Number of sites filtered based on maximum mean depth
 79234 of 1555651 

Total number of sites filtered
 616124 of 2092541 

Remaining sites
 1476417 
 
Variants will now be composed into SNPs and INDels

Number of SNPs before filtering for call rate and minor allele frequency
 2636976 

Number of INDels
 462075 

Number of SNPs with 90% call rate, MAF of 0.01, and excess heterozygous loci removed
Number of SNPs with 90% call rate, MAF of 0.05, and excess heterozygous loci removed
Number of SNPs with 95% call rate, MAF of 0.01, and excess heterozygous loci removed
Number of SNPs with 95% call rate, MAF of 0.05, and excess heterozygous loci removed
Number of SNPs with 100% call rate, MAF of 0.01, and excess heterozygous loci removed
Number of SNPs with 100% call rate, MAF of 0.05, and excess heterozygous loci removed
Number of biallelic SNPs with 100% call rate, MAF of 0.01, and excess heterozygous loci removed
Number of biallelic SNPs with 100% call rate, MAF of 0.05, and excess heterozygous loci removed

Filter stats and filtered VCF files stored in TRS.TRSdp5g75.nDNA.filterstats
Both are stored in the filtered directory

Now we can continue to work with SNP.TRS.TRSdp5g75.nDNA.FIL.vcf.gz in the new SNPs directory
Make a new directory within RISG_dDocent_working
```{bash}
cd /home/ccaillon/RISG_dDocent_working
mkdir RISG_SNP_Filtering_working
cd RISG_SNP_Filtering_working

#Link SNP filtered VCF file to new directory
ln -s /home/ccaillon/RISG_dDocent_working/raw.vcf/SNPs/SNP.TRS.TRSdp5g75.nDNA.FIL.vcf.gz
```

Do not do a second minimum read depth filter of 10 like Amy or ROD_CADO project, otherwise too much missing data in "bad" individuals (keep dp = 5).

MAF filtering for FreeBayes Output. Keeps SNPs with minor allele frequency ≥ 0.1% (extremely permissive because keeping almost all variants).
I decompressed the .vcf.gz file before using multi.maf.sh script.
```{bash}
curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/untested/multi.maf.sh
chmod +x multi.maf.sh #makes script executable
gunzip -c SNP.TRS.TRSdp5g75.nDNA.FIL.vcf.gz > SNP.TRS.TRSdp5g75.nDNA.FIL.vcf #decompress .vcf.gz file without removing it
./multi.maf.sh SNP.TRS.TRSdp5g75.nDNA.FIL.vcf 0.001 SNP.TRSdp5g75maf.nDNA.FIL
rm SNP.TRS.TRSdp5g75.nDNA.FIL.vcf #then remove heavy .vcf file
```

After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 2616479 out of a possible 2636976 Sites
Run Time = 1979.00 seconds

Use a custom script called filter_missing_ind.sh to filter out bad individuals = filter on individual missingness.
Here it's mostly just to observe the % of missing data within individuals. We are working with a small number of individuals, so it's likely we will not remove any.
I am also gzipping all vcf files little by little in this directory to free up space in KITT.
```{bash}
curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/filter_missing_ind.sh
chmod +x filter_missing_ind.sh
./filter_missing_ind.sh SNP.TRSdp5g75maf.nDNA.FIL.recode.vcf SNP.TRSdp5g75mafMI.nDNA.FIL

#To compress:
gzip SNP.TRSdp5g75maf.nDNA.FIL.recode.vcf #remove by default the previous .vcf file
gzip SNP.TRSdp5g75mafMI.nDNA.FIL.recode.vcf
```

After filtering, kept 239 out of 239 Individuals
Outputting Individual Missingness
After filtering, kept 2616479 out of a possible 2616479 Sites
Run Time = 292.00 seconds

                                          Histogram of % missing data per individual
     Number of Occurrences
       25 ++-----------+-------------+------------+------------+------------+-------------+------------+-----------++
          +            +       ****  +            +            'totalmissing' using (bin($1,binwidth)):(1.0) ****** +
          |                    *  *                                                                                 |
          |                    *  *                                                                                 |
          |                    *  *                                                                                 |
       20 ++                 ***  *                                                                                ++
          |                  * *  *                                                                                 |
          |                  * *  *                                                                                 |
          |               **** *  *                                                                                 |
       15 ++              *  * *  *  ***                                                                           ++
          |               *  * *  *  * *            ****                                                            |
          |            ****  * *  **** *            *  *                                                            |
          |            *  *  * *  *  * *       **** *  *                                                            |
          |            *  *  * *  *  * *    ****  * *  *    ****                                                    |
       10 ++           *  *  * *  *  * ******  *  * *  **** *  *                                                   ++
          |            *  *  * *  *  * *  * *  *  * *  *  * *  *                                                    |
          |       **** *  *  * *  *  * *  * *  *  * *  *  * *  *                                                    |
          |    ****  ***  *  * *  *  * *  * *  *  ***  *  ***  ****                                                 |
        5 ++   *  *  * *  *  * *  *  * *  * *  *  * *  *  * *  *  *                                                ++
          |    *  *  * *  *  * *  *  * *  * *  *  * *  *  * *  *  *                                                 |
          |    *  *  * *  *  * *  *  * *  * *  *  * *  *  * *  *  * ****                                            |
          |    *  *  * *  *  * *  *  * *  * *  *  * *  *  * *  *  ***  *********    ****   **********               |
          +    *  *  * *  *  * *  *  * *  * *  *  * *  *  * *  *  * *  *  * *  ******  *****        ************    +
        0 ++---*************************************************************************************************---++
          0           0.05          0.1          0.15         0.2          0.25          0.3          0.35         0.4
                                                       % of missing data

The 85% cutoff would be 0.193592
Would you like to set a different cutoff, yes or no
no

Excluding individuals in 'exclude' list
After filtering, kept 206 out of 239 Individuals
Outputting VCF file...
After filtering, kept 2616479 out of a possible 2616479 Sites
Run Time = 2029.00 seconds

```{bash}
#List of the worst 13 samples:
cat <(head -1 SNP.TRSdp5g75mafMI.nDNA.FIL.imiss ) <(mawk '!/F_MI/' SNP.TRSdp5g75mafMI.nDNA.FIL.imiss | sort -k5 -r -n ) | head -14 | column -t
```

INDV        N_DATA   N_GENOTYPES_FILTERED  N_MISS  F_MISS
NB_DB_3277  2616479  0                     977896  0.373745
HC_DB_3041  2616479  0                     949933  0.363058
HC_DB_3039  2616479  0                     830048  0.317239
M_DB_3257   2616479  0                     822398  0.314315
BAR_NB_2    2616479  0                     772858  0.295381
MW_CB_3406  2616479  0                     752615  0.287644
HA_CB_3334  2616479  0                     736631  0.281535
MW_CB_3399  2616479  0                     710222  0.271442
MCD_NB_6    2616479  0                     700202  0.267612
SR_DB_3071  2616479  0                     670155  0.256129
SR_DB_3061  2616479  0                     666463  0.254718
MW_CB_3405  2616479  0                     646696  0.247163
CS_DB_3004  2616479  0                     641953  0.24535

Notes:
The histogram shows the distribution of % missing data across indivdiuals.
Diagnostic with .imiss file = outputting individual missingness.
N_MISS = number of missing genotypes / F_MISS = fraction of missing genotypes.
Sites/loci are unchanged because this step is only removing individuals.

Because this step filtered out individuals 2 individuals in BAR_NB population (and so only 8 individuals left), I won't use it moving forward, instead I'll keep going with SNP.TRSdp5g75maf.nDNA.FIL.recode.vcf.gz

Use a second custom script pop_missing_filter.sh to filter loci that have high missing data values within a single population.
for this step, we need the populations file popmap previously created by dDocent.
Moving forward with three different filtering pathways: popmap filter with matching max-missing filter of 0.1 (more stringent), 0.5 (medium stringency), and 0.8 (less stringent), in order to test different levels of filtering to see if there are significant differences in the results.
The goal of pop_missing_filter.sh is to remove loci/sites that have too much missing data within populations, not to remove individuals.
I modified the pop_missing_filter script to recognize the gzipped vcf file input.
```{bash}
cd /home/ccaillon/RISG_dDocent_working/RISG_SNP_Filtering_working

#Link popmap file
ln -s ../popmap

curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/pop_missing_filter.sh
chmod +x pop_missing_filter.sh
```

More stringent level with pop matching max-missing filtering of 0.1:
```{bash}
./pop_missing_filter.sh SNP.TRSdp10maf.nDNA.FIL.recode.vcf.gz popmap 0.1 1 SNP.TRSdp10mafPM9.nDNA.FIL
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 25449 out of a possible 2616479 Sites
Run Time = 363.00 seconds (this time per population)

So with 0.1 as missingness threshold within each population, it flags loci with more than 10% missing data in that population. It also means that locus must have at least 90% completeness within a population. Because of $4 = 1, any locus that fails >10% missingness in at least one population gets removed. So this filter is meant to eliminate loci that are poorly genotyped in any population.

Medium stringent level with pop matching max-missing filtering of 0.5:
```{bash}
./pop_missing_filter.sh SNP.TRSdp10maf.nDNA.FIL.recode.vcf.gz popmap 0.5 1 SNP.TRSdp10mafPM5.nDNA.FIL
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 566332 out of a possible 2616479 Sites
Run Time = 752.00 seconds (this time per population)

Less stringent level with pop matching max-missing filtering of 0.8:
```{bash}
./pop_missing_filter.sh SNP.TRSdp10maf.nDNA.FIL.recode.vcf.gz popmap 0.8 1 SNP.TRSdp10mafPM2.nDNA.FIL
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 1787524 out of a possible 2616479 Sites
Run Time = 1702.00 seconds (this time per population)

Filter out any sites with less than % overall call rate and MAF of 0.001.
Repeat the same filtering level for the overall call rate as the popmap filter step, specific to each vcf filtering pathway.

More stringent filtering level with max-missing of 0.9:
```{bash}
vcftools --vcf SNP.TRSdp10mafPM9.nDNA.FIL.recode.vcf --recode-INFO-all --max-missing 0.9 --maf 0.001 --out SNP.TRSdp10mafPM9g9.nDNA.FIL --recode
```
Output: 
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 25381 out of a possible 25449 Sites
Run Time = 21.00 seconds

Medium stringent filtering level with max-missing of 0.5:
```{bash}
vcftools --vcf SNP.TRSdp10mafPM5.nDNA.FIL.recode.vcf --recode-INFO-all --max-missing 0.5 --maf 0.001 --out SNP.TRSdp10mafPM5g5.nDNA.FIL --recode
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 544397 out of a possible 566332 Sites
Run Time = 420.00 seconds

Less stringent filtering level with max-missing of 0.2:
```{bash}
vcftools --vcf SNP.TRSdp10mafPM2.nDNA.FIL.recode.vcf --recode-INFO-all --max-missing 0.2 --maf 0.001 --out SNP.TRSdp10mafPM2g2.nDNA.FIL --recode
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 1648440 out of a possible 1787524 Sites
Run Time = 1555.00 seconds






FIRST METHOD

Next step is to mark any genotypes with less than 10 reads as missing (stricter depth filter)
```{bash}
vcftools --gzvcf SNP.TRS.TRSdp5g75.nDNA.FIL.vcf.gz --minDP 10 --recode --recode-INFO-all --out SNP.TRSdp10.nDNA.FIL
#vcftools --gzvcf SNP.TRS.TRSdp5g75.nDNA.FIL.vcf.gz --minDP 10 --recode --recode-INFO-all --stdout | bcftools view --threads 24 -O z -o SNP.TRSdp10.nDNA.FIL.vcf.gz
#bcftools to compressed output directly
```

After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 2636976 out of a possible 2636976 Sites
Run Time = 2287.00 seconds

MAF filtering for FreeBayes Output. Keeps SNPs with minor allele frequency ≥ 0.1% (extremely permissive because keeping almost all variants).
```{bash}
curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/untested/multi.maf.sh
chmod +x multi.maf.sh #makes script executable
./multi.maf.sh SNP.TRSdp10.nDNA.FIL.recode.vcf 0.001 SNP.TRSdp10maf.nDNA.FIL
```

After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 2616479 out of a possible 2636976 Sites
Run Time = 2111.00 seconds

Use a custom script called filter_missing_ind.sh to filter out bad individuals = filter on individual missingness.
Here it's mostly just to observe the % of missing data within individuals. We are working with a small number of individuals, so it's likely we will not remove any.
I am also gzipping all vcf files little by little in this directory to free up space in KITT.
```{bash}
curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/filter_missing_ind.sh
chmod +x filter_missing_ind.sh
./filter_missing_ind.sh SNP.TRSdp10maf.nDNA.FIL.recode.vcf SNP.TRSdp10mafMI.nDNA.FIL

#To gzip:
gzip SNP.TRSdp10.nDNA.FIL.recode.vcf #remove by default the previous .vcf file
gzip SNP.TRSdp10maf.nDNA.FIL.recode.vcf
```

After filtering, kept 239 out of 239 Individuals
Outputting Individual Missingness
After filtering, kept 2616479 out of a possible 2616479 Sites
Run Time = 263.00 seconds

                                          Histogram of % missing data per individual                                    
       12 +---------------------------------------------------------------------------------------------------------+   
          |            +             +            **           +            +             +            +            |   
          |                                       **          'totalmissin** using (bin($1,binwidth)):(1.0) ******* |   
          |                                       **                      **                                        |   
       10 |-+                                     **                      **    ***                               +-|   
          |                                       **                      **    * *                                 |   
          |                                     ****  **                  **    * *                                 |   
          |                                     * **  **                  **    * *                                 |   
        8 |-+                                   * **  **              **  **    * *                               +-|   
          |                                     * **  **              **  **    * *                                 |   
          |                                     * **  *****           **  ***** * *                                 |   
        6 |-+                               ***** ******* *   **  *********** * * *                               +-|   
          |                                 * *** *** *** *   **  *** *** *** * * *                                 |   
          |                               *** *** *** *** *********** *** *** * * *                                 |   
          |                               *** *** *** *** *** *** *** *** *** * * *                                 |   
        4 |-+            ***      **      *** *** *** *** *** *** *** *** *** *** **   ***                        +-|   
          |              * *      **      *** *** *** *** *** *** *** *** *** *** **   * *                          |   
          |        ***   * *  **  ****  ***** *** *** *** *** *** *** *** *** *** **   * ***                        |   
          |        * *   * *  **  ** *  * *** *** *** *** *** *** *** *** *** *** **   * * *                        |   
        2 |-+      * *** * * *** *** **** *** *** *** *** *** *** *** *** *** *** **   * * *****  *****           +-|   
          |        * * * * * *** *** **** *** *** *** *** *** *** *** *** *** *** **   * * *** *  *   *             |   
          |  ******* * *** ********* **** *** *** *** *** *** *** *** *** *** *** ****** * *** ****   *****         |   
          |  ** *  * * * * * *** *** **** *** *** *** *** *** *** *** *** *** *** *** ** *+*** *  *   *+ **         |   
        0 +---------------------------------------------------------------------------------------------------------+   
         0.1          0.2           0.3          0.4          0.5          0.6           0.7          0.8          0.9  
                                                       % of missing data                                                
                                                                                                                        
The 85% cutoff would be 0.631647
Would you like to set a different cutoff, yes or no
no

Excluding individuals in 'exclude' list
After filtering, kept 206 out of 239 Individuals
Outputting VCF file...
After filtering, kept 2616479 out of a possible 2616479 Sites
Run Time = 1720.00 seconds

```{bash}
#List of the worst 12 samples:
cat <(head -1 SNP.TRSdp10mafMI.nDNA.FIL.imiss ) <(mawk '!/F_MI/' SNP.TRSdp10mafMI.nDNA.FIL.imiss | sort -k5 -r -n ) | head -13 | column -t
```

INDV        N_DATA   N_GENOTYPES_FILTERED  N_MISS   F_MISS
HC_DB_3041  2616479  0                     2161000  0.825919
NB_DB_3277  2616479  0                     2135470  0.816162
M_DB_3257   2616479  0                     2025951  0.774304
HC_DB_3039  2616479  0                     2020543  0.772237
BAR_NB_2    2616479  0                     1980649  0.75699
MW_CB_3406  2616479  0                     1933136  0.738831
HA_CB_3334  2616479  0                     1918054  0.733067
MW_CB_3399  2616479  0                     1884969  0.720422
CS_DB_3004  2616479  0                     1884894  0.720393
SR_DB_3061  2616479  0                     1868810  0.714246
SR_DB_3071  2616479  0                     1846989  0.705906
MW_CB_3405  2616479  0                     1840049  0.703254

Notes:
The histogram shows the distribution of % missing data across indivdiuals.
Diagnostic with .imiss file = outputting individual missingness.
N_MISS = number of missing genotypes / F_MISS = fraction of missing genotypes.
Sites/loci are unchanged because this step is only removing individuals.

Because this step filtered out individuals, I won't use it moving forward, instead I'll keep going with SNP.TRSdp10maf.nDNA.FIL.recode.vcf.gz

Use a second custom script pop_missing_filter.sh to filter loci that have high missing data values within a single population.
for this step, we need the populations file popmap previously created by dDocent.
Moving forward with three different filtering pathways: popmap filter with matching max-missing filter of 0.1 (more stringent), 0.5 (medium stringency), and 0.8 (less stringent), in order to test different levels of filtering to see if there are significant differences in the results.
The goal of pop_missing_filter.sh is to remove loci/sites that have too much missing data within populations, not to remove individuals.
I modified the pop_missing_filter script to recognize the gzipped vcf file input.
```{bash}
cd /home/ccaillon/RISG_dDocent_working/RISG_SNP_Filtering_working

#Link popmap file
ln -s ../popmap

curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/pop_missing_filter.sh
chmod +x pop_missing_filter.sh
```

More stringent level with pop matching max-missing filtering of 0.1:
```{bash}
./pop_missing_filter.sh SNP.TRSdp10maf.nDNA.FIL.recode.vcf.gz popmap 0.1 1 SNP.TRSdp10mafPM9.nDNA.FIL
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 25449 out of a possible 2616479 Sites
Run Time = 363.00 seconds (this time per population)

So with 0.1 as missingness threshold within each population, it flags loci with more than 10% missing data in that population. It also means that locus must have at least 90% completeness within a population. Because of $4 = 1, any locus that fails >10% missingness in at least one population gets removed. So this filter is meant to eliminate loci that are poorly genotyped in any population.

Medium stringent level with pop matching max-missing filtering of 0.5:
```{bash}
./pop_missing_filter.sh SNP.TRSdp10maf.nDNA.FIL.recode.vcf.gz popmap 0.5 1 SNP.TRSdp10mafPM5.nDNA.FIL
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 566332 out of a possible 2616479 Sites
Run Time = 752.00 seconds (this time per population)

Less stringent level with pop matching max-missing filtering of 0.8:
```{bash}
./pop_missing_filter.sh SNP.TRSdp10maf.nDNA.FIL.recode.vcf.gz popmap 0.8 1 SNP.TRSdp10mafPM2.nDNA.FIL
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 1787524 out of a possible 2616479 Sites
Run Time = 1702.00 seconds (this time per population)

Filter out any sites with less than % overall call rate and MAF of 0.001.
Repeat the same filtering level for the overall call rate as the popmap filter step, specific to each vcf filtering pathway.

More stringent filtering level with max-missing of 0.9:
```{bash}
vcftools --vcf SNP.TRSdp10mafPM9.nDNA.FIL.recode.vcf --recode-INFO-all --max-missing 0.9 --maf 0.001 --out SNP.TRSdp10mafPM9g9.nDNA.FIL --recode
```
Output: 
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 25381 out of a possible 25449 Sites
Run Time = 21.00 seconds

Medium stringent filtering level with max-missing of 0.5:
```{bash}
vcftools --vcf SNP.TRSdp10mafPM5.nDNA.FIL.recode.vcf --recode-INFO-all --max-missing 0.5 --maf 0.001 --out SNP.TRSdp10mafPM5g5.nDNA.FIL --recode
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 544397 out of a possible 566332 Sites
Run Time = 420.00 seconds

Less stringent filtering level with max-missing of 0.2:
```{bash}
vcftools --vcf SNP.TRSdp10mafPM2.nDNA.FIL.recode.vcf --recode-INFO-all --max-missing 0.2 --maf 0.001 --out SNP.TRSdp10mafPM2g2.nDNA.FIL --recode
```
Output:
After filtering, kept 239 out of 239 Individuals
Outputting VCF file...
After filtering, kept 1648440 out of a possible 1787524 Sites
Run Time = 1555.00 seconds


